### ISSUE TITLE
The server example panics after sending 9Mb from 6972 

### ISSUE THREAD

**Issue by batonius** [smoltcp-rs/smoltcp#41]
**Scenario:**
- `RUST_BACKTRACE=1 cargo run --example server -- tap0`
- `nc 192.168.69.1 6972 > nc_out`

**Result:**
```
[     3.605s] <- EthernetII src=2a-d3-30-70-6c-b6 dst=02-00-00-00-00-01 type=IPv4
                \ IPv4 src=192.168.69.100 dst=192.168.69.1 proto=TCP
                 \ TCP src=56036 dst=6972 seq=2966042689 ack=1329360159 win=65535 len=0
[     3.605s] (socket::tcp): [4]192.168.69.1:6972:192.168.69.100:56036: tx buffer: dequeueing 65535 octets (now 0)
thread 'main' panicked at 'assertion failed: acked.len() == ack_len', src/socket/tcp.rs:999:12
stack backtrace:
[...]
   5: std::panicking::begin_panic_new
             at /checkout/src/libstd/panicking.rs:553
   6: smoltcp::socket::tcp::TcpSocket::process
             at src/socket/tcp.rs:999
   7: <smoltcp::iface::ethernet::Interface<'a, 'b, 'c, DeviceT>>::process_tcp
             at ./src/iface/ethernet.rs:417
   8: <smoltcp::iface::ethernet::Interface<'a, 'b, 'c, DeviceT>>::process_ipv4
             at ./src/iface/ethernet.rs:315
   9: <smoltcp::iface::ethernet::Interface<'a, 'b, 'c, DeviceT>>::process_ethernet
             at ./src/iface/ethernet.rs:220
  10: <smoltcp::iface::ethernet::Interface<'a, 'b, 'c, DeviceT>>::socket_ingress
             at ./src/iface/ethernet.rs:144
  11: <smoltcp::iface::ethernet::Interface<'a, 'b, 'c, DeviceT>>::poll
             at ./src/iface/ethernet.rs:126
  12: server::main
             at examples/server.rs:184
[...]
```
```bash
ls -lh nc_out
-rw-r--r-- 1  9.7M Sep 12 21:52 nc_out
```

**Comment by whitequark** [comment]
Pretty sure this was fixed in eff0e0b90e73ab66929a24e996ff3836ca43a590.
