### ISSUE TITLE
"Attempt to subtract with overflow" when `verbose` feature enabled in debug

### ISSUE THREAD

**Issue by JakkuSakura** [smoltcp-rs/smoltcp#486]
```rust
Jun 08 06:50:00.792 DEBUG ThreadId(06) public_api::api_controller::imp: Sending {"id":1623135000792573295,"method":"SUBSCRIBE","params":["ethusdt@kline_1m"]}
Jun 08 06:50:01.017 DEBUG ThreadId(02) smoltcp::iface::interface: cannot process ingress packet: checksum error    
Jun 08 06:50:01.017 DEBUG ThreadId(02) smoltcp::iface::interface: packet dump follows:
EthernetII src=06-db-18-9e-7d-66 dst=06-67-ae-9e-c3-0a type=IPv4
\ IPv4 src=54.249.160.7 dst=172.31.43.77 proto=TCP
 \ TCP src=443 dst=30510 psh seq=1905798223 ack=247 win=110 len=1024 (checksum incorrect)    
Jun 08 06:50:01.017 DEBUG ThreadId(02) devourer::runtime::smoltcp: Error Checksum
Jun 08 06:50:02.030 DEBUG ThreadId(02) smoltcp::socket::tcp: #0:172.31.43.77:30510:54.249.160.7:443: received a keep-alive or window probe packet, will send an ACK    
Jun 08 06:50:02.659 ERROR main panic: thread 'main' panicked at 'attempt to subtract with overflow': /root/.cargo/git/checkouts/smoltcp-d6a83fd2b0891566/7e62f68/src/socket/tcp.rs:909
   0: log_panics::init::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/log-panics-2.0.0/src/lib.rs:52:25
   1: std::panicking::rust_panic_with_hook
             at /rustc/4e3e6db011c5b482d2bef8ba02274657f93b5e0d/library/std/src/panicking.rs:629:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/4e3e6db011c5b482d2bef8ba02274657f93b5e0d/library/std/src/panicking.rs:517:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/4e3e6db011c5b482d2bef8ba02274657f93b5e0d/library/std/src/sys_common/backtrace.rs:141:18
   4: rust_begin_unwind
             at /rustc/4e3e6db011c5b482d2bef8ba02274657f93b5e0d/library/std/src/panicking.rs:515:5
   5: core::panicking::panic_fmt
             at /rustc/4e3e6db011c5b482d2bef8ba02274657f93b5e0d/library/core/src/panicking.rs:92:14
   6: core::panicking::panic
             at /rustc/4e3e6db011c5b482d2bef8ba02274657f93b5e0d/library/core/src/panicking.rs:50:5
   7: smoltcp::socket::tcp::TcpSocket::recv_impl
             at /root/.cargo/git/checkouts/smoltcp-d6a83fd2b0891566/7e62f68/src/socket/tcp.rs:909:30
   8: smoltcp::socket::tcp::TcpSocket::recv_slice
             at /root/.cargo/git/checkouts/smoltcp-d6a83fd2b0891566/7e62f68/src/socket/tcp.rs:938:9
   9: <devourer::network::smoltcp::tcp_channel::TcpChannel as std::io::Read>::read
             at /home/ubuntu/trading-project/devourer/src/network/smoltcp/tcp_channel.rs:179:15
  10: <devourer::network::smoltcp::tcp_channel::TcpChannel as futures_io::if_std::AsyncRead>::poll_read
             at /home/ubuntu/trading-project/devourer/src/network/smoltcp/tcp_channel.rs:200:23
  11: <&mut T as futures_io::if_std::AsyncRead>::poll_read
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-io-0.3.15/src/lib.rs:337:17
  12: <async_tls::rusttls::stream::Stream<IO,S>::complete_read_io::Reader<T> as std::io::Read>::read
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/async-tls-0.11.0/src/rusttls/stream.rs:58:23
  13: rustls::msgs::deframer::MessageDeframer::read
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rustls-0.19.1/src/msgs/deframer.rs:64:25
  14: rustls::session::SessionCommon::read_tls
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rustls-0.19.1/src/session.rs:648:9
  15: <rustls::client::ClientSession as rustls::session::Session>::read_tls
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rustls-0.19.1/src/client/mod.rs:708:9
  16: async_tls::rusttls::stream::Stream<IO,S>::complete_read_io
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/async-tls-0.11.0/src/rusttls/stream.rs:67:23
  17: async_tls::rusttls::stream::Stream<IO,S>::complete_inner_io
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/async-tls-0.11.0/src/rusttls/stream.rs:116:23
  18: async_tls::rusttls::stream::Stream<IO,S>::complete_io
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/async-tls-0.11.0/src/rusttls/stream.rs:47:9
  19: <async_tls::client::MidHandshake<IO> as core::future::future::Future>::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/async-tls-0.11.0/src/client.rs:62:24
  20: <async_tls::connector::Connect<IO> as core::future::future::Future>::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/async-tls-0.11.0/src/connector.rs:175:59
  21: <devourer::network::common::tls_channel::TlsChannelBuilder<Builder> as devourer::network::common::channel_builder::AsyncChannelBuilder>::connect::{{closure}}
             at /home/ubuntu/trading-project/devourer/src/network/common/tls_channel.rs:34:30
  22: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4e3e6db011c5b482d2bef8ba02274657f93b5e0d/library/core/src/future/mod.rs:80:19
  23: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/4e3e6db011c5b482d2bef8ba02274657f93b5e0d/library/core/src/future/future.rs:120:9
  24: <devourer::network::common::websocket_channel::WebsocketChannelBuilder<Builder> as devourer::network::common::channel_builder::AsyncChannelBuilder>::connect::{{closure}}
             at /home/ubuntu/trading-project/devourer/src/network/common/websocket_channel.rs:79:26
  25: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4e3e6db011c5b482d2bef8ba02274657f93b5e0d/library/core/src/future/mod.rs:80:19
  26: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/4e3e6db011c5b482d2bef8ba02274657f93b5e0d/library/core/src/future/future.rs:120:9
  27: <devourer::network::common::auto_reconnect_channel::AutoReconnectChannelReconnectState<InnerBuilder> as core::future::future::Future>::poll::{{closure}}::{{closure}}
             at /home/ubuntu/trading-project/devourer/src/network/common/auto_reconnect_channel.rs:181:43
  28: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/4e3e6db011c5b482d2bef8ba02274657f93b5e0d/library/core/src/future/mod.rs:80:19
  29: <devourer::network::common::auto_reconnect_channel::AutoReconnectChannelReconnectState<InnerBuilder> as core::future::future::Future>::poll
             at /home/ubuntu/trading-project/devourer/src/network/common/auto_reconnect_channel.rs:184:19
  30: futures_util::future::future::FutureExt::poll_unpin
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.15/src/future/future/mod.rs:562:9
  31: devourer::network::common::auto_reconnect_channel::AutoReconnectChannel<InnerBuilder>::try_get_channel
             at /home/ubuntu/trading-project/devourer/src/network/common/auto_reconnect_channel.rs:282:23
  32: <devourer::network::common::auto_reconnect_channel::AutoReconnectChannel<Builder> as futures_io::if_std::AsyncWrite>::poll_write
             at /home/ubuntu/trading-project/devourer/src/network/common/auto_reconnect_channel.rs:392:23
  33: <public_api::api_controller::imp::PublicApiControllerIoImpl<ApiIo> as core::future::future::Future>::poll
             at src/api_controller.rs:259:23
  34: <alloc::boxed::Box<F,A> as core::future::future::Future>::poll
             at /rustc/4e3e6db011c5b482d2bef8ba02274657f93b5e0d/library/alloc/src/boxed.rs:1711:9
  35: futures_util::future::future::FutureExt::poll_unpin
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.15/src/future/future/mod.rs:562:9
  36: <public_api::runtime::PublicTradingRuntimeIoPoll<Runtime> as core::future::future::Future>::poll
             at src/runtime.rs:306:19
  37: <std::panic::AssertUnwindSafe<F> as core::future::future::Future>::poll
             at /rustc/4e3e6db011c5b482d2bef8ba02274657f93b5e0d/library/std/src/panic.rs:363:9
  38: <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.15/src/future/future/catch_unwind.rs:36:42
  39: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/4e3e6db011c5b482d2bef8ba02274657f93b5e0d/library/std/src/panic.rs:346:9
  40: std::panicking::try::do_call
             at /rustc/4e3e6db011c5b482d2bef8ba02274657f93b5e0d/library/std/src/panicking.rs:401:40
  41: __rust_try
  42: std::panicking::try
             at /rustc/4e3e6db011c5b482d2bef8ba02274657f93b5e0d/library/std/src/panicking.rs:365:19
  43: std::panic::catch_unwind
             at /rustc/4e3e6db011c5b482d2bef8ba02274657f93b5e0d/library/std/src/panic.rs:433:14
  44: <futures_util::future::future::catch_unwind::CatchUnwind<Fut> as core::future::future::Future>::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.15/src/future/future/catch_unwind.rs:36:9
  45: <futures_util::future::future::remote_handle::Remote<Fut> as core::future::future::Future>::poll
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.15/src/future/future/remote_handle.rs:105:29
  46: glommio::task::raw::RawTask<F,R,S>::run
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/glommio-0.4.1/src/task/raw.rs:461:20
  47: glommio::task::task_impl::Task::run
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/glommio-0.4.1/src/task/task_impl.rs:115:18
  48: glommio::executor::LocalExecutor::run_one_task_queue
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/glommio-0.4.1/src/executor/mod.rs:1077:25
  49: glommio::executor::LocalExecutor::run_task_queues
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/glommio-0.4.1/src/executor/mod.rs:1040:17
  50: glommio::executor::LocalExecutor::run::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/glommio-0.4.1/src/executor/mod.rs:1162:27
  51: scoped_tls::ScopedKey<T>::set
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/scoped-tls-1.0.0/src/lib.rs:137:9
  52: glommio::executor::LocalExecutor::run
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/glommio-0.4.1/src/executor/mod.rs:1141:9
  53: async_executors::exec::glommio_ct::GlommioCt::block_on
             at /root/.cargo/git/checkouts/async_executors-ace842206f9e52fc/84e47cd/src/exec/glommio_ct.rs:53:3
  54: main::main
             at examples/main.rs:39:5
  55: core::ops::function::FnOnce::call_once
             at /rustc/4e3e6db011c5b482d2bef8ba02274657f93b5e0d/library/core/src/ops/function.rs:227:5
  56: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/4e3e6db011c5b482d2bef8ba02274657f93b5e0d/library/std/src/sys_common/backtrace.rs:125:18
  57: std::rt::lang_start::{{closure}}
             at /rustc/4e3e6db011c5b482d2bef8ba02274657f93b5e0d/library/std/src/rt.rs:49:18
  58: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/4e3e6db011c5b482d2bef8ba02274657f93b5e0d/library/core/src/ops/function.rs:259:13
      std::panicking::try::do_call
             at /rustc/4e3e6db011c5b482d2bef8ba02274657f93b5e0d/library/std/src/panicking.rs:401:40
      std::panicking::try
             at /rustc/4e3e6db011c5b482d2bef8ba02274657f93b5e0d/library/std/src/panicking.rs:365:19
      std::panic::catch_unwind
             at /rustc/4e3e6db011c5b482d2bef8ba02274657f93b5e0d/library/std/src/panic.rs:433:14
      std::rt::lang_start_internal
             at /rustc/4e3e6db011c5b482d2bef8ba02274657f93b5e0d/library/std/src/rt.rs:34:21
  59: std::rt::lang_start
             at /rustc/4e3e6db011c5b482d2bef8ba02274657f93b5e0d/library/std/src/rt.rs:48:5
  60: main
  61: __libc_start_main
  62: <unknown>
```

**Comment by JakkuSakura** [comment]
Ok, after some inspection, it's probably because my code uses unsafe, and these two lines are not atomic.
```rust
let _old_length = self.rx_buffer.len();
let (size, result) = f(&mut self.rx_buffer);
```
So `_old_length - size` overflows. 
I think it's it's better to write them as `_old_length as isize - size as isize` to avoid panicking. Sinse it's for debugging purpose,  inaccurate negative numbers in unsafe edge cases are fine.
Or just `self.rx_buffer.len()` if there were no mutable reference to `rx_buffer`
