### ISSUE TITLE
Server example does not work anymore

### ISSUE THREAD

**Issue by pothos** [smoltcp-rs/smoltcp#70]
Hello,

I think change https://github.com/m-labs/smoltcp/pull/57 requires the server example to be updated or something else is not correct?

```
RUST_BACKTRACE=1 cargo +stable run --example server tap0 
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `target/debug/examples/server tap0`
[     0.001s] (socket::set): [0]: adding
[     0.001s] (socket::set): [1]: adding
[     0.001s] (socket::set): [2]: adding
[     0.001s] (socket::set): [3]: adding
[     0.001s] (socket::set): [4]: adding
[     0.001s] (socket::tcp): #1:*:6969: state=CLOSED=>LISTEN
[     0.001s] (socket::tcp): #2:*:6970: state=CLOSED=>LISTEN
[     0.001s] (socket::tcp): #3:*:6971: state=CLOSED=>LISTEN
[     0.001s] (socket::tcp): #4:*:6972: state=CLOSED=>LISTEN
[     0.001s] (iface::ethernet): cannot dispatch response packet: buffer space exhausted
thread 'main' panicked at 'poll error: Exhausted', /checkout/src/libcore/result.rs:906:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:381
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:397
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:611
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:572
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:522
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:498
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:71
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:41
  10: <core::result::Result<T, E>>::expect
             at /checkout/src/libcore/result.rs:799
  11: server::main
             at examples/server.rs:188
  12: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:99
  13: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:459
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:61
  14: main
  15: __libc_start_main
  16: _start
```

**Comment by whitequark** [comment]
Fixed in f239e36.
